name = "planning-gcal"
main = "index.js"
compatibility_date = "2026-05-20"
observability = { enabled = true }
account_id = "686385718410239110ea2fe1bccf43be"

[[kv_namespaces]]
binding = "PLANNING_DB"
id = "8c380577a5d8482c95ef6aceea259b55"
